CREATE DATABASE PTTK_GOT;

USE PTTK_GOT;


CREATE TABLE IF NOT EXISTS zones(
	IdZone INT NOT NULL AUTO_INCREMENT UNIQUE,
	ZoneName VARCHAR(30) NOT NULL UNIQUE,
	CHECK(ZoneName<>''),
	PRIMARY KEY(IdZone)
);
